export const SET_ERROR = 'setError'
export const SET_USER = 'setUser'
export const CLEAR_USER = 'clearUser'
export const SET_GAME_REPORT = 'setGameReport'
export const SET_GAME_INTEL = 'setGameIntel'
